import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem-vindo ao <a href="https://nextjs.org">RTS RPG Game!</a>
        </h1>

        <p className={styles.description}>
          Baixe o client
          <a
            href="https://firebasestorage.googleapis.com/v0/b/rtsrpg-game.appspot.com/o/client.zip?alt=media&token=5f41e21c-644a-4d31-bfa9-c25bce1356ad"
            className={styles.card}
          >
            <b style={{ color: "gold" }}>Clicando aqui</b>
          </a>
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Sobre &rarr;</h2>
            <p>Em breve mais detalhes sobre esse jogo espetacular!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Powered by PlaylinesDev
        </a>
      </footer>
    </div>
  );
};

export default Home;
