import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem-vindo ao <a href="https://nextjs.org">RTS RPG Game!</a>
        </h1>

        <p className={styles.description}>
          Após baixar, descompacte em alguma pasta e rode o arquivo RtsRpg.exe
          <br />
          Ao abrir, preencha apenas o seu nome de usuário e clique em conectar.
          <br />
          Para se mover, use as teclas ASDW. Aperte ESC para liberar o mouse e
          use para girar a visão ao seu redor.
          <br />
          Essa é toda a jogabilidade disponível no momento, mas fique atento
          para as próximas atualizações
          <br />
          <br />
          <br />
          Baixe o client (Nova versão).
          <br />
          <br />
          <br />
          <a
            href="https://firebasestorage.googleapis.com/v0/b/rtsrpg-game.appspot.com/o/client.zip?alt=media&token=662e4566-1e05-4262-994f-5270e77ee2f9"
            className={styles.card}
          >
            <b style={{ color: "gold", fontSize: "2em" }}>Clicando aqui</b>
          </a>
        </p>
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Powered by PlaylinesDev
        </a>
      </footer>
    </div>
  );
};

export default Home;
